name: Push Nuget Packages

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --verbosity normal
    - name: Pack
      run: dotnet pack -c Release --output nuget-packages
    - name: Push nuget packages
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

